language: ruby
rvm:
- 2.1
script: bundle exec middleman build
deploy:
- provider: s3
  access_key_id: AKIAIA5ECJTPIGFZOPXA
  secret_access_key:
    secure: Q2/HJgjr4TY9rqNaTuZ3+A9TdyXvw07SLPYBXueyoJZAOp2N12nD9XbmXgNsMomLKZ3REB4DoacTK5OOoeX/Aiap6DhR1VUMPZpYFjHdpvP2e6cV7WtD9cDGs9rQstuCkTV/smBPl4Y0rUC/52fyL3trpkoBXoLX8SbDiWeuZbc=
  bucket: til.justincampbell.me
  local-dir: build
  skip_cleanup: true
  on:
    branch: master
